name: Master release

on:
  push:
    branches:
      - master-c11

jobs:
  master-c11:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm test

      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git config --global pull.ff only

      - run: |
          set -euo pipefail
          # Make sure the remote branch exists or bootstrap it
          TMP="$(mktemp -d)"
          cp -r .git "$TMP/"
          cd "$TMP"
          git fetch
          git switch -c master-c11-dist
          git branch --set-upstream-to=origin/master-c11-dist master-c11-dist && { exit 0; }
          git add .
          git commit -m "First empty commit"
          git push --set-upstream origin master-c11-dist

      - uses: actions/checkout@v4
        with:
          ref: master-c11-dist
          path: master-c11-dist
      - run: |
          set -euo pipefail

          wdir="$(pwd)"
          branchDir="${GITHUB_WORKSPACE}/master-c11-dist"

          cp -r "${wdir}/bin" "${branchDir}/"
          cp -r "${wdir}/browser" "${branchDir}/"
          cp -r "${wdir}/src" "${branchDir}/"
          cp "${wdir}/package.json" "${branchDir}/"
          cp "${wdir}/package-lock.json" "${branchDir}/"

          cd "${branchDir}"
          git add .
          git commit -m "release-${GITHUB_SHA}" --allow-empty
          git push
          git tag "release-${GITHUB_SHA}"
          git push --tags

          echo "Released: release-${GITHUB_SHA}"

      - uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.sha }}
